### ISSUE TITLE
PAS controls not updating properly

### ISSUE THREAD

**Issue by lo-co** [NOAA-CSD/nicholas#10]

**Comment by lo-co** [comment]
Initial state of power looks bad - both lasers are set to `TRUE` for the enable state at boot and the CVT looks like it is saying `FALSE`.

**Comment by nicholaslwagner** [comment]
I saw this same issue this morning. 3/6/2018

**Comment by lo-co** [comment]
Client was expecting strings but was getting numbers for the heater control.  Fixed in most recent release.
