### ISSUE TITLE
Hanbay Valve turns 180 degrees. It should only turn 90 degrees

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/nicholas#12]
The Hanbay valves turn 180 degrees between the two states on the client (chan 1 or chan 2). With respect to the flow system a 180 degree turn is the same state. A 90 degree turn is need between the two states.

Hanbay valve is set to 3 position functionality (DIP 8 is off. I confirmed this by visual inspection.)  

Here are the position definition from the hanbay manual

| Position | Pin 1 | Pin 2 |
| ---------- | ------ | ------- | 
| Center |   HIGH | HIGH |
| right | LOW | HIGH |
| left | HIGH | LOW |

Based on these definitions and the 180 degree turn, the current software must be cycling between right and left position.  I would like to cycle between the  center and left positions.

in the left position (High, Low),  Chan1  is downstream of the filter and Chan2 is sampling
in the center position (high, high), chan1 is sampling and Chan 2 is down stream of the filter

**Comment by lo-co** [comment]
So, when the control is `Channel 1`, the signal sent to the FPGA is `FALSE`.  When the control is `Channel 2`, then the signal sent to the FPGA is `TRUE`.  `Channel x` indicates that `x` is sampling (not downstream of filter).

**Comment by lo-co** [comment]
So, in the FPGA, pin 1 (labeled `hb1 ctl 1`) is now *always* `TRUE` (or high) and we `not` the value of the input described above for pin 2 (labeled `hb ctl 2`).

**Comment by nicholaslwagner** [comment]
The hanbay is now working correctly.
