### ISSUE TITLE
PAS frequency plot offset by 1200

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/nicholas#14]
On client, when in the PAS page in the freqeuncy domain. The x-axis is offset by 1200. 

Matt - you are already aware of this. I'm just trying to collect all of the issues in one spot.

**Comment by lo-co** [comment]
So, the reason this is defaulting to 1200 is that I am working with some truncation routines that I am trying to make more general.  I have fixed this in the most recent iteration of the client but this will likely create more disruptions.
