### ISSUE TITLE
Honeywell PPTs and RH probes are not returning data

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/nicholas#17]
These have worked in the past. 2 weeks ago. may be the RS485 cable is broke. I'll ring it out.

**Comment by lo-co** [comment]
I am checking this on the low level to see if these even show up.  Commands for data on these is as follows:

*  `Send 2` 
* `*01P1`
* `02P1`

**Comment by lo-co** [comment]
So, I don't know what happened here but the `Transceiver Mode` was reset to `4 Wire`.  Reset this again to `2 Wire Auto`.
**Still can not see the Vaisala probe.**

**Comment by nicholaslwagner** [comment]
Last night both the honeywells and the vaisala were return data. occaionally, the honeywell would report 0 pressure. So there are some communication lapses be it would recover in the next iteration.

**Comment by lo-co** [comment]
The communication issue that you are speaking of is associated with  configuration on the PPTs.  Will take a look at this but closing for now.
