### ISSUE TITLE
Set FC to volume flow

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/nicholas#20]
Cell 0, cell 1, mirror purge FCs should be set to control volumetric flow.

 The O3 flow controller should be set to mass flow.

**Comment by lo-co** [comment]
This has to be done on the physical device and can not be done in software (I think).

**Comment by nicholaslwagner** [comment]
On the physical flow controls I changed cell1 and cell0 to control on volume. They were controlling on mass

The mirror purge was set to control on volume. I didn't change it.

I confirmed that the O3 rate is set to control on mass.

Once the software is running I'll see if this worked.

Nick

**Comment by lo-co** [comment]
Confirmed
