### ISSUE TITLE
Multiple columns with the same name in data file

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/nicholas#24]
These columns appear twice.
cell_0.P
cell_0.Q
cell_0.T
cell_1.P
cell_1.Q
cell_1.T

**Comment by lo-co** [comment]
Changed in INI file - MFC label was set to `cell_0`.  Changed *all*  MFCs to have the prefix `mfc_`.  May change the other one to indicate that it is referring to the CRD.
