### ISSUE TITLE
SOAP datafile

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/nicholas#26]
I'm looking for a few pieces of data in the file and not finding them.

* Hanbay position
* heater setpoints
* heater percentage on
* honeywell pressures
* honeywell temperatures
* vaisala RH
* vaisala temp.

**Comment by lo-co** [comment]
Will add these.  Going to bundle some of the bool values and just let you unwind them as we discussed previously.  FYI - I am very certain the hygrometer values are in there, but will check.  There should be three values associated with this - temperature, dewpoint, and RH.

**Comment by lo-co** [comment]
Adding `Heater Data` object for handling heater data.  This will contain 

* PID enable state
* setpoint
* current heater dc

The current value of the temperature is already returned with the rest of the temperatures.

**Comment by lo-co** [comment]
New return packet will look something like:

```
{
  "general": {
    "temperatures": {
      "pas_cell_1": 0,
      "pas_cell_2": 0,
      "pas_las_head_1": 0,
      "pas_las_head_2": 0,
      "box_exit": 0,
      "crd_heater": 0,
      "box_inlet": 0,
      "crd_laser_head": 0,
      "cjc": 0,
      "autozero": 0
    },
    "msgs": [],
    "interlock": false
  },
  "GenDataObj": {
    "enable": false,
    "sp": 0,
    "dc": 0
  }
}
```

The entry `GenObjData` will be replaced by the ids of the three heater objects.

This will also fix the issue of how to get the dc value back to the UI without creating a continually updating CVT.  Yay!

**Comment by lo-co** [comment]
In `Controller::Pre-Launch Init`, the three heater objects are initialized with the names 

* `crd_heater`
* `pas_1_heater`
* `pas_2_heater`

The data will be written to file as `id.[data]` where data is 

* `enable`
* `setpoint`
* `dc`

in the data file.  In the json packet.  

The data is packed in the VI `Controller::Common`, retrieved from the CVT and the global variable `DC`.

**Comment by lo-co** [comment]
So, with regards to the hygrometer and ppts, the file writing functionality was missing from the implementation.

**Comment by nicholaslwagner** [comment]
An additional data file issue:  There is only one PAS speaker (on/off) data column (there should be speaker on/off data for both PAS channels) and it does not appear to have real data in it. (I remember turn the speaker on/off while collection the data file. I'm looking at the data file that we collected during Thursday 3/15 on the DC8 during integration.

**Comment by lo-co** [comment]
Everything should be there on the next check in.  Adding a new entry to the `dio_state`.  This is a 32-bit hexadecimal number representing the following DIO states:

* pas_laser_relay_1
* pas_heater_1
* pas_heater_2
* pas_laser_relay_2
* pas_spk_enable_1
* pas_spk_enable_2
* hanbay_pos
* fan_enable
* crd_laser_enable
* crd_heater_enable
* vacuum_pump
* ac_spare
* uv_enable
* solenoid_1
* solenoid_2
* spare_dc_relay_1
* usb_hub_relay
* spare_dc_relay_2
* fp_aux_1
* fp_aux_2

**Comment by lo-co** [comment]
In python, you can decode the hex string with a function that looks like:

```
def hex_byte_to_bits(hex_byte):
    binary_byte = bin(int(hex_byte, base=16))
    # Use zfill to pad the string with zeroes as we want all 8 digits of the byte.
    bits_string = binary_byte[2:].zfill(8)
    return [int(bit) for bit in bits_string]
```

**Comment by nicholaslwagner** [comment]
Matt, Could you check the order of the hexadecimal number.  Is pas_laser_relay_1 most or least significant digit?
