### ISSUE TITLE
Set CRD and PAS laser to be ON at startup

### ISSUE THREAD

**Issue by nicholaslwagner** [NOAA-CSD/nicholas#33]
I think the CRD is off by default.

**Comment by lo-co** [comment]
This should be a configuration issue.  But it appears that the configuration is not being read properly.

**Comment by lo-co** [comment]
Not certain what is going on here - if you look in the logs, the CRD is coming up with the laser enabled.  Will look further.

**Comment by lo-co** [comment]
Lasers are configured to be enabled at startup.  It works.  Closing now.
